modLoader="javafml" #mandatory# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="LGPL-3.0-or-later"
#issueTrackerURL="https://github.com/Bomb787/minute-rice/issues" #optional
[[mods]] #mandatory
modId="minute_rice" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Minute Rice" #mandatory
credits="rbasamoyai, for the idea." #optional
authors="Bomb787" #optional
displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

# The description text for the mod (multi line!) (#mandatory)
description='''
Adds Minute Rice.
'''
[[dependencies.minute_rice]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.minute_rice]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
